image: nixos/nix:latest

variables:
  NIX_PATH: "nixpkgs=channel:nixos-unstable"
  NIX_CONFIG: "experimental-features = nix-command flakes"

pages:
  before_script:
    - nix-env -iA nixpkgs.git
  script:
    - nix build
    - mkdir images
    - cp -r result/* public/
  artifacts:
    paths:
      - images
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
